### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sheoak** [roddhjav/pass-audit#17]
At the end of the audit I have this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 349, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 338, in main
    weak = audit.zxcvbn()
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 261, in zxcvbn
    results = zxcvbn(password, user_inputs=user_input + path.split("/"))
  File "/usr/lib/python3.7/site-packages/zxcvbn/__init__.py", line 28, in zxcvbn
    result = scoring.most_guessable_match_sequence(password, matches)
  File "/usr/lib/python3.7/site-packages/zxcvbn/scoring.py", line 204, in most_guessable_match_sequence
    optimal_match_sequence = unwind(n)
  File "/usr/lib/python3.7/site-packages/zxcvbn/scoring.py", line 181, in unwind
    for candidate_l, candidate_g in optimal['g'][k].items():
IndexError: list index out of range
```

```
$ pass audit -V
pass audit 1.0.1
$ python --version
Python 3.7.3
```

**Comment by roddhjav** [comment]
Hi, I did few changes that directly modify the way this feature works. Could you test from the master branch if you have the same error. I yes, could you please provide me with a more details, like the kind of password entry you test it against: what format? what kind of metadata?

**Comment by sheoak** [comment]
Thank you for the reply. Actually I did some tests and when a password is empty then I get this error (sometimes I leave the first row empty but fill other details)

**Comment by sheoak** [comment]
Actually it might not be the only case, because pass grep -c "^$" now does not return anything but still have the issue. I have to find which pass gives an error and I will give you more details.

**Comment by sheoak** [comment]
it's actually a different error now:

```
  .  Auditing whole store - this may take some time
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 393, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 385, in main
    weak = audit.zxcvbn()
  File "/usr/lib/python3.7/site-packages/pass_audit.py", line 300, in zxcvbn
    user_input.remove(password)
ValueError: list.remove(x): x not in list
```

**Comment by sheoak** [comment]
Ok so the error is simple, if the first line is in this form:

```key: value```

It will raise the error. If there is no space it will work.

**Comment by roddhjav** [comment]
That's my fault. Sorry about that. Fixed.

**Comment by RaitoBezarius** [comment]
I encountered again this error on Android credentials from Chrome.

**Comment by RaitoBezarius** [comment]
On a empty-password (first line was empty.)

**Comment by roddhjav** [comment]
Thank for this. Fixed with a11e71c

**Comment by anarcat** [comment]
is there a plan to ship this bugfix in a new release? :)

**Comment by roddhjav** [comment]
Yes, As they have been a few changes lately, I plan to do a new release somewhere this weekend.

**Comment by roddhjav** [comment]
Release done.
