### ISSUE TITLE
Filter out/warn about paswordless entries

### ISSUE THREAD

**Issue by Iipin** [roddhjav/pass-audit#24]
I got the following error when auditing my store:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/pass_audit/__main__.py", line 151, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pass_audit/__main__.py", line 144, in main
    breached, weak = pass_audit(msg, data)
  File "/usr/lib/python3.9/site-packages/pass_audit/__main__.py", line 107, in pass_audit
    weak = audit.zxcvbn()
  File "/usr/lib/python3.9/site-packages/pass_audit/audit.py", line 88, in zxcvbn
    results = zxcvbn(password, user_inputs=user_input)
  File "/usr/lib/python3.9/site-packages/zxcvbn/__init__.py", line 28, in zxcvbn
    result = scoring.most_guessable_match_sequence(password, matches)
  File "/usr/lib/python3.9/site-packages/zxcvbn/scoring.py", line 204, in most_guessable_match_sequence
    optimal_match_sequence = unwind(n)
  File "/usr/lib/python3.9/site-packages/zxcvbn/scoring.py", line 181, in unwind
    for candidate_l, candidate_g in optimal['g'][k].items():
IndexError: list index out of range
```

Turns out it got thrown when checking an entry storing just OTP metadata and no password (i.e., with empty first line). The root of the problem seems to be that `zxcvbn.zxcvbn` crashes when given an empty string, but even so, I believe that `pass-audit` should recognize that the file has nothing to audit and ignore it/emit a warning. The fix seems to be quite simple, so I can prepare a PR soon.

**Comment by Iipin** [comment]
Oh nevermind, it is already solved, sorry – closing.
