### ISSUE TITLE
`pass audit /` hangs

### ISSUE THREAD

**Issue by tadfisher** [roddhjav/pass-audit#3]
Trying to audit all of my passwords, I ran:

`pass audit`

Since I am on the release version, I get:

` [x] Error: pass-names not present. See 'pass audit -h'`

So I tried the following:

`pass audit -v /`

Nothing is printed, and after several minutes, I killed the process:

```
^CTraceback (most recent call last):
  File "/usr/lib/password-store/audit/audit.py", line 258, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/audit/audit.py", line 232, in main
    for path in store.list(arg.paths):
  File "/usr/lib/password-store/audit/audit.py", line 130, in list
    for file in glob.glob(prefix + '*/**/*.gpg', recursive=True):
  File "/usr/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/lib/python3.6/glob.py", line 110, in _glob2
    yield from _rlistdir(dirname, dironly)
  File "/usr/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  File "/usr/lib/python3.6/glob.py", line 138, in _rlistdir
    for y in _rlistdir(path, dironly):
  [Previous line repeated 65 more times]
  File "/usr/lib/python3.6/glob.py", line 133, in _rlistdir
    names = list(_iterdir(dirname, dironly))
  File "/usr/lib/python3.6/glob.py", line 122, in _iterdir
    for entry in it:
KeyboardInterrupt
```

Perhaps the extension is recursing through the `.git` subdirectory or the actual filesystem root? I would expect this to behave similarly to `pass audit ""`, which does happen to work on the release version.

**Comment by roddhjav** [comment]
Hi Tadfisher,

This issue has been fixed on the master branch. I plan to release soon. But because `pass-audit` is still in development it's not that easy to provide stable release. Therefore for now, please use the master branch.

I'll inspect the second issue because it is not directly linked to the first error and it could possible have consequences at other moment. Thank for reporting this.
